.include "m324padef.inc"
.equ MISO=6
.cseg
.org 0x0000
LDI R17,(1<<MISO)
OUT DDRB,R17

LDI R17,(1<<SPE0)
OUT SPCR0,R17
SBI DDRC,5
SBI PORTC,5

MAIN:
RCALL KEY_PAD_SCAN
CPI R24,0xFF
BRNE AGAIN
CBI PORTC,5
RJMP MAIN

AGAIN: 
SBI PORTC,5
OUT SPDR0,R23
WAIT:
LDS R19,SPSR0
SBRS R19,7
RJMP WAIT
IN R18,SPDR0
RJMP MAIN
 
KEY_PAD_SCAN:;PD_0 -> PD_3: OUTPUT, COL;PD_4 -> PD_7: INPUT, ROW
LDI R16, $0F
OUT DDRA, R16
LDI R16, $F0
OUT PORTA, R16
CALL BUTTON
LDI R22, 0B11110111 ;INITIAL COLUMN MASK
LDI R24, 0 ;INITIAL PRESSED ROW VALUE
LDI R23, 3 ;SCANNING COLUMN INDEX
KEYPAD_SCAN_LOOP:
OUT PORTA, R22
SBIC PINA, 4 ;CHECK ROW 0
RJMP KEYPAD_SCAN_CHECK_COL2
RJMP KEYPAD_SCAN_FOUND ;ROW 0 IS PRESSED
KEYPAD_SCAN_CHECK_COL2:
SBIC PINA, 5 ;CHECK ROW 1
RJMP KEYPAD_SCAN_CHECK_COL3
LDI R24, 1 ;ROW 1 IS PRESSED
RJMP KEYPAD_SCAN_FOUND
KEYPAD_SCAN_CHECK_COL3:
SBIC PINA, 6 ;CHECK ROW 2
RJMP KEYPAD_SCAN_CHECK_COL4
LDI R24, 2 ;ROW 2 IS PRESSED
RJMP KEYPAD_SCAN_FOUND
KEYPAD_SCAN_CHECK_COL4:
SBIC PINA, 7 ;CHECK ROW 3
RJMP KEYPAD_SCAN_NEXT_ROW
LDI R24, 3 ;ROW 3 IS PRESSED
RJMP KEYPAD_SCAN_FOUND
KEYPAD_SCAN_NEXT_ROW:
CPI R23, 0
BREQ KEYPAD_SCAN_NOT_FOUND
ROR R22
DEC R23
RJMP KEYPAD_SCAN_LOOP
KEYPAD_SCAN_FOUND:    ; combine row and column to get key value (0-15);key code = row*4 + col    
LSL R24 ; shift row value 4 bits to the left
LSL R24    
ADD R24, R23 ; add row value to column value
RET
KEYPAD_SCAN_NOT_FOUND:
LDI R24, 0XFF ;NO KEY PRESSED
RET
BUTTON:LDI R17, 50
DEBOUNCING_1:
IN R16, PINA
CPI R16, $FF ;DETECT STATUS OF BUTTON
BREQ BUTTON
DEC R17
BRNE DEBOUNCING_1
RET